import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rahul
 */
public class Sales extends javax.swing.JFrame {
    
    private static float grandTotal;

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        genId();
        grandTotal=0;
        
    }
void genId()
{
try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
       
        PreparedStatement stm=con.prepareStatement("select MAX(sid)+1 from sale");
        ResultSet rs1 = stm.executeQuery();
        while(rs1.next())
            
        {
        jTextField1.setText(rs1.getString(1));
        }
      
           
           
       }catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(null,e);
    
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jTextField7.setText("jTextField7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setText("Sales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 77));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Type", "Size", "Weight", "Price", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 470, 330));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setText("Search By Name");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, -1, 36));

        jTextField8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 190, 36));

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton6.setText("<-Back");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jButton1.setText("ADD TO BILL");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 220, 49));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Bill Id");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 122, 47));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 111, 40));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Contact No.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 159, 42));

        jTextField2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 200, 41));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 49));

        jTextField9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 200, 40));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setText("Type");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 86, 46));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Angle", "Channel", "Wire" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 90, 37));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setText("Weight");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, 58));

        jTextField4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 200, 40));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel7.setText("Price Per Kg");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 169, 46));

        jTextField5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 200, 43));

        jTextField10.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 550, 250, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setText("Sub Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 142, 65));

        jTextField6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 200, 40));


        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 150, 40));



        pack();
    }// </editor-fold>                        

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {                                        
                try{  
          Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
          String txt=jTextField2.getText();
          PreparedStatement stm=con.prepareStatement("select cust_name from customer where cust_mobile like '%"+txt+"%'");
          ResultSet rs=stm.executeQuery();
          if(rs.next())
          {
              jTextField9.setText(rs.getString(1));
          }
          con.close(); 
       }catch(ClassNotFoundException | SQLException e){
           JOptionPane.showMessageDialog(null,e);
       }

    }                                       

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
if(jComboBox1.getSelectedItem().toString()=="Angle")
{
jComboBox2.removeAllItems();
jComboBox2.addItem("25mm x 25mm x 3mm");
jComboBox2.addItem("40mm x 40mm x 5mm");
jComboBox2.addItem("50mm x 50mm x 5mm");
}
else if(jComboBox1.getSelectedItem().toString()=="Channel")
    {
     jComboBox2.removeAllItems();   
    jComboBox2.addItem("100mm x 50mm");
    jComboBox2.addItem("125mm x 65mm");
    jComboBox2.addItem("70mm x 35mm");
    }                                          
else if(jComboBox1.getSelectedItem().toString()=="Wire")
{
    jComboBox2.removeAllItems();
jComboBox2.addItem("1 mm");
jComboBox2.addItem("2 mm");
jComboBox2.addItem("3 mm");
}
       
       
    }                                          

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
try {
           Date date = Calendar.getInstance().getTime();
        DateFormat dateGet = new SimpleDateFormat("dd-MM-yyyy");
        String dd = dateGet.format(date);
        String s="";
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
            
            
            
            PreparedStatement stm = con.prepareStatement("insert into sale values (?,?,?,?,?,?,?,?,?)");
            stm.setString(1,jTextField1.getText());//sid
            stm.setString(2, jTextField2.getText());
            stm.setString(3, jTextField9.getText());
            stm.setString(4, jComboBox1.getSelectedItem().toString());
            stm.setString(5, jTextField4.getText());//weight
            stm.setString(6, jTextField5.getText());//price
            stm.setString(7, jTextField6.getText());//total
            stm.setString(8 , dd);//date
            stm.setString(9 , jComboBox2.getSelectedItem().toString());//date
           stm.execute();
           JOptionPane.showMessageDialog(null, "Added to Bill");
           updateStock(jComboBox2.getSelectedItem().toString(),jComboBox1.getSelectedItem().toString(),jTextField4.getText());
           grandTotal=grandTotal+Float.parseFloat(jTextField6.getText());
           jTextField10.setText(String.format("%.2f",grandTotal)); 
           jTextField4.setText("");
           jTextField5.setText("");
           jTextField6.setText("");
           
           Class.forName("com.mysql.cj.jdbc.Driver");
           Connection con3 =DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
          
        PreparedStatement stm2=con3.prepareStatement("select * from sale where sid ='"+jTextField1.getText()+"'");

          ResultSet rs1=stm2.executeQuery();
          jTable1.setModel(DbUtils.resultSetToTableModel(rs1));
          con.close();    
                          
            
        } 
        catch (Exception e) {
            System.out.println(e);
        }
         
    }                                        
void sell()
{

}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
Home h=new Home();
h.setVisible(true);
this.dispose();// TODO add your handling code here:
        // TODO add your handling code here:
    }                                        

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       
        finalizeOrder(jTextField1.getText(),jTextField9.getText(),jTextField2.getText(),jTextField10.getText());
        
        jTextField1.setText(String.valueOf(Integer.parseInt(jTextField1.getText())+1));
         try{
        Class.forName("com.mysql.cj.jdbc.Driver");
         
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
                JasperDesign j = JRXmlLoader.load("C:\\Users\\Rahul Patel\\Desktop\\rs\\src\\Bill.jrxml");
                String q = "Select * from bill where billid ="+jTextField1.getText();
                HashMap p= new HashMap();
                //p.put("total", Integer.toString(s1));
                JRDesignQuery uq = new JRDesignQuery();
                uq.setText(q);
                j.setQuery(uq);
                JasperReport jrp = JasperCompileManager.compileReport(j);
                JasperPrint jp = JasperFillManager.fillReport(jrp ,null,con);
                JasperViewer.viewReport(jp, rootPaneCheckingEnabled);
               
            
        } 
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {                                        
              float a= Float.parseFloat(jTextField5.getText());
        float b=Float.parseFloat(jTextField4.getText());
        float c = a*b;
       
        jTextField6.setText(Float.toString(c));
    }                                       

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration                   

    private void updateStock(String size, String type, String weight) {
        System.out.println("Size: "+size);
        System.out.println("Type: "+type);
        System.out.println("Weight: "+weight);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
            
            PreparedStatement stm1 = con.prepareStatement("select weight from stock where type='"+type+"' and size='"+size+"'");
           
           ResultSet rs = stm1.executeQuery();
           while(rs.next())
           {
                String i = rs.getString(1);
                 int ans = Integer.parseInt(i)-Integer.parseInt(weight);
           System.out.println(ans);
          PreparedStatement pstmt = con.prepareStatement("update stock set weight ='"+ans+"' where type='"+type+"' and size='"+size+"'");
        
                    pstmt.execute();
           }

        }
        catch(Exception e)
        {
            System.out.println(e.getMessage());
        }
// throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void finalizeOrder(String billId, String name, String contact, String gTotal) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
      try{
          
          Class.forName("com.mysql.cj.jdbc.Driver");
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
            
           
            
            PreparedStatement stm = con.prepareStatement("INSERT INTO bill VALUES(?,?,?,?)");
            stm.setString(1,billId);//sid
            stm.setString(2,name);//sid
            stm.setString(3,contact);//sid
            stm.setString(4,gTotal);//sid
            
             stm.execute();
           JOptionPane.showMessageDialog(null, "Bill Finalized");
          
      }catch(Exception e){
          System.out.println(e);
      }
        grandTotal=0;
        jTextField10.setText(String.valueOf(grandTotal)); 
    }
}
