//import java.sql.Connection;
//import java.sql.DriverManager;
//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
//import java.sql.SQLException;
//import java.text.DateFormat;
//import java.text.SimpleDateFormat;
//import java.util.Date;
//import java.util.HashMap;
//import java.util.logging.Level;
//import java.util.logging.Logger;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JRDesignQuery;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.xml.JRXmlLoader;
//import net.sf.jasperreports.view.JasperViewer;
//
///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//
///**
// *
// * @author Rahul Patel
// */
//public class SalesReport extends javax.swing.JFrame {
//
//    /**
//     * Creates new form SalesReport
//     */
//    public SalesReport() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jCalendar1 = new com.toedter.calendar.JCalendar();
//        jLabel1 = new javax.swing.JLabel();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jCalendar2 = new com.toedter.calendar.JCalendar();
//        jCalendar3 = new com.toedter.calendar.JCalendar();
//        jButton3 = new javax.swing.JButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
//        jLabel1.setText("Enter Date to generate report");
//
//        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
//        jButton1.setText("Click Here To Generate  Report");
//        jButton1.setToolTipText("");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jButton2.setText("<-Back");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });
//
//        jButton3.setText("jButton3");
//        jButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton3ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                .addGap(179, 605, Short.MAX_VALUE)
//                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(84, 84, 84))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(53, 53, 53)
//                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 443, Short.MAX_VALUE))
//            .addGroup(layout.createSequentialGroup()
//                .addGap(31, 31, 31)
//                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(149, 149, 149))
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(jButton2))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(213, 213, 213)
//                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(361, 361, 361)
//                        .addComponent(jButton3)))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addGap(55, 55, 55)
//                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                    .addGroup(layout.createSequentialGroup()
//                        .addContainerGap()
//                        .addComponent(jButton2)
//                        .addGap(68, 68, 68)
//                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addGap(77, 77, 77)
//                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(jCalendar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jButton3)
//                .addGap(32, 32, 32))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//                 try{
//        Class.forName("com.mysql.cj.jdbc.Driver");
//
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
//                JasperDesign j = JRXmlLoader.load("C:\\Users\\Rahul Patel\\Desktop\\rs\\src\\Bill.jrxml");
//                 Date s = jCalendar1.getDate();
//                 DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
//                  String d1 = d.format(s);
//                String q = "Select * from bill where datee ='"+d1+"'";
//
//                JRDesignQuery uq = new JRDesignQuery();
//                uq.setText(q);
//                j.setQuery(uq);
//                JasperReport jrp = JasperCompileManager.compileReport(j);
//                JasperPrint jp = JasperFillManager.fillReport(jrp ,null,con);
//                JasperViewer.viewReport(jp, rootPaneCheckingEnabled);
//
//
//        }
//        catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (JRException ex) {
//            System.out.println(ex);        }
//
//
//    }
//
//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
//Home h=new Home();
//h.setVisible(true);
//this.dispose();// TODO add your handling code here:
//        // TODO add your handling code here:
//    }
//Float s1=0.0f;
//    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
//        Date s = jCalendar2.getDate();
//        DateFormat d = new SimpleDateFormat("yyyy-MM-dd");
//        String d1 = d.format(s);
//         Date s2 = jCalendar3.getDate();
//         String d2= d.format(s2);
//
//    try{
//        Class.forName("com.mysql.cj.jdbc.Driver");
//
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
//
//                PreparedStatement stm = con.prepareStatement("select gtotal from bill where datee between '"+d1+"' and '"+d2+"' ");
//              ResultSet rs = stm.executeQuery();
//              while (rs.next())
//              {
//
//               s1 =s1+Float.parseFloat(rs.getString(1));
//              }
//              System.out.println(Float.toString(s1));
//        }
//    catch(Exception e)
//    {
//        System.out.println(e);
//    }        try{
//        Class.forName("com.mysql.cj.jdbc.Driver");
//
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/finaldb","root","1234");
//
//                JasperDesign j = JRXmlLoader.load("C:\\Users\\Rahul Patel\\Desktop\\rs\\src\\Bill.jrxml");
//                String q = "select * from bill where datee between '"+d1+"' and '"+d2+"' ";
//                HashMap h = new HashMap();
//                h.put("total",Float.toString(s1));
//                JRDesignQuery uq = new JRDesignQuery();
//                uq.setText(q);
//                j.setQuery(uq);
//                JasperReport jrp = JasperCompileManager.compileReport(j);
//                JasperPrint jp = JasperFillManager.fillReport(jrp ,h,con);
//                JasperViewer.viewReport(jp, rootPaneCheckingEnabled);
//
//
//        }
//        catch (ClassNotFoundException | SQLException ex) {
//            Logger.getLogger(Purchase.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (JRException ex) {
//            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
//        }        // TODO add your handling code here:
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SalesReport().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private com.toedter.calendar.JCalendar jCalendar1;
//    private com.toedter.calendar.JCalendar jCalendar2;
//    private com.toedter.calendar.JCalendar jCalendar3;
//    private javax.swing.JLabel jLabel1;
//    // End of variables declaration
//}
